spring:
  application:
    name: JpaPractice
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:practicedb
management:
  endpoints:
    web:
      exposure:
        include: info, metrics, loggers
      base-path: /monitor
